<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwmtpiv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwmtpiv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMwmtpiv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMwmtpiv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMwmtpiv\appProdProjectContainer([
    'container.build_hash' => 'Mwmtpiv',
    'container.build_id' => 'bf9010a2',
    'container.build_time' => 1572449653,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwmtpiv');
